export default {
	disclaimer: [
		"Think about your desire/idea/goal.",
		"No matter where are you now: at the start or halfway to the final. Ask yourself some questions and  take a step towards the result.",
		"",
		"Good luck!",
		"Katerina Kostyukova",
		"Professional Certified Coach (PCC)",
		"Next",
		"#50questions_istok",
	],
	about: {
		business: "Business trainings",
		history: "Our history",
		about: "International coaching center ISTOK is one of the leading providers of coaching services in Russia. We teach coaching in open and corporate formats, we offer individual and team coaching services according to international standards for clients anywhere in the world. The team of the center is professional ICF coaches, experienced business coaches, mentors and supervisors.",
		heading: "About company",
		services: "Company Services",
		training: "Training",
		coaching: "Coaching",
		facilitation: "Facilitation"
	},
	card: {
		question: "Question",
		of: "of",
		card: "Card",
		now: "Now cards:",
		oops: "Oops...",
		over: "You run out of cards, do you want to add a few more questions?",
		add: "Add",
		heading: "Cards",
		answer: "Answer"
	},
	login: [
		"Sign in",
		"E-mail",
		"Password",
		"Sign in",
		"Or",
		"Skip this step",
		"Sign up",
		"Sign up",
		"Password Confirmation"
	],
	menu: [
		"Cards",
		"About company",
		"Tasks list",
		"Settings",
		"Menu",
		"Order a deck"
	],
	settings: [
		"Main",
		"Turn off",
		"Turn on",
		"notifications",
		"Reset all",
		"Log out",
		"Order a deck with questions",
		"Settings"
	],
	todoText: [
		"New task",
		"Tasks list"
	],
	questions: [
		"What kind of person do you think you would need to be in order to achieve your goal?",
		"What challenges do you think you would need to face to achieveyour goal?",
		"What could make you feel as though you are getting closer to achieving your goal?",
		"What kind of inspirational words would you say to yourself before you begin moving towards your goal?",
		"What challenges do you think you would need to consider?",
		"What do you need to believe in, in order to succeed?",
		"What really motivates you to move towards your goal?",
		"What will you change in your tomorrow in order to get the result in time?",
		"What changes should happen in your mindset so that you can achieve the result?",
		"What are the resources required to achieve your goal? How will availability/deficiency of them affect your plan?",
		"What do you consider as the best solution?",
		"What do you really want?",
		"What are you willing to start with?",
		"Who else can help you achieve your goal?",
		"What opportunities will the desired result give you?",
		"What do you want to devote the most time to?",
		"What is your focus of attention?",
		"In what directions do you want to develop?",
		"Where does your power lie?",
		"What is the biggest obstacle in achieving your goal? What are the ways of overcoming it?",
		"What is important to change about yourself in order to achieve the desired result?",
		"What or whom do you want to get better for?",
		"How will you recognize that the desired result has been achieved?",
		"What steps towards your desired life can you take today?",
		"What are the key steps towards your goal?",
		"In achieving the desired result what is the thing that only you are capable of doing?",
		"What are you really good at?",
		"What opportunities can you use to move towards your goal in a new way?",
		"What do you want to contribute to the achievement of your goal?",
		"Whose goal is this?",
		"What is valuable to you about achieving your goal?",
		"What other goals can be of higher priority than the one you're thinking of?",
		"What level should your energy reach so that you can fulfill the goal?",
		"How excited are you about your vision?",
		"What are the key results of the goal achievement?",
		"What can make your goal even more important?",
		"Who can inspire you to achieve the best result?",
		"If you had half as much time to achieve the result, how would you change your plan?",
		"Which of your strengths are you going to use to achieve your goal?",
		"What will be the effect for you and other people?",
		"What is the most interesting aspect for you about achieving your goal?",
		"In what form do you want to create your goal achievement plan?",
		"Who do you want to ask for advice?",
		"What inspires you most about your goal?",
		"What do you want to learn on your way towards the goal?",
		"How can your goal be formulated to sound even more inspiring?",
		"If you decided to make a breakthrough, what would it be?",
		"What is the most ambitious way to define/phrase your purpose?",
		"What is your main reason to accomplish your goal in full and on time?",
		"What will you actively do to try to fulfill your goal?",
	],
	orderDeck: {
		name: "Name",
		phone: "Phone number",
		order: "Order",
		successText: "You have successfully ordered a deck of question cards. Our manager will contact you in the near future.",
		backButton: "Back",
		heading: "Order a deck"
	}
	
}